version: "3.7"
services:
  mysql-db:
    image: mysql:8.0.17
    environment:
      MYSQL_DATABASE: board
      MYSQL_ROOT_PASSWORD: boardproject
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - backend

  server:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    networks:
      - backend
    command: ["./wait-for-it.sh", "mysql-db:3306", "--", "java","-jar","/app.jar"]

networks:
  backend: